
import streamlit as st
import pandas as pd
import joblib
from pathlib import Path

# Page configuration
st.set_page_config(
    page_title="E-commerce Revenue Predictor",
    page_icon="📊",
    layout="wide"
)

# Load the saved model
MODEL_PATH = Path(__file__).parent / "revenue_model.joblib"

@st.cache_resource
def load_model():
    return joblib.load(MODEL_PATH)

st.title("E-commerce Revenue Predictor")
st.write(
    "Estimate order revenue using a trained "
    "Decision Tree Regression model."
)

st.info(
    "This is an educational prediction tool trained on "
    "synthetic sales data. Predictions are estimates, "
    "not guaranteed real-world revenue."
)

# Sidebar inputs
st.sidebar.header("Order Details")

quantity = st.sidebar.slider(
    "Quantity",
    min_value=1,
    max_value=5,
    value=2
)

unit_price = st.sidebar.slider(
    "Unit Price (₹)",
    min_value=399,
    max_value=4999,
    value=1499,
    step=100
)

discount = st.sidebar.slider(
    "Discount",
    min_value=0,
    max_value=20,
    value=10,
    step=5
) / 100

category = st.sidebar.selectbox(
    "Product Category",
    [
        "Electronics",
        "Clothing",
        "Home & Kitchen",
        "Beauty",
        "Books"
    ]
)

region = st.sidebar.selectbox(
    "Region",
    ["East", "West", "North", "South"]
)

payment_method = st.sidebar.selectbox(
    "Payment Method",
    [
        "UPI",
        "Credit Card",
        "Debit Card",
        "Net Banking",
        "Cash on Delivery"
    ]
)

# Show selected details
st.subheader("Selected Order")

col1, col2, col3 = st.columns(3)

col1.metric("Quantity", quantity)
col2.metric("Unit Price", f"₹{unit_price:,.2f}")
col3.metric("Discount", f"{discount * 100:.0f}%")

st.write(f"**Category:** {category}")
st.write(f"**Region:** {region}")
st.write(f"**Payment Method:** {payment_method}")

# Prediction
if st.button("Predict Revenue", type="primary"):
    try:
        model = load_model()

        input_data = pd.DataFrame([{
            "Quantity": quantity,
            "Unit_Price": unit_price,
            "Discount": discount,
            "Category": category,
            "Region": region,
            "Payment_Method": payment_method
        }])

        prediction = model.predict(input_data)[0]

        st.subheader("Prediction Result")

        st.metric(
            label="Estimated Order Revenue",
            value=f"₹{prediction:,.2f}"
        )

        st.caption(
            "The result is generated by the trained "
            "machine learning model."
        )

        # Compare with the direct revenue formula
        calculated_revenue = (
            quantity * unit_price * (1 - discount)
        )

        with st.expander("Understand this prediction"):
            st.write(
                f"Revenue calculated directly from the "
                f"dataset formula: ₹{calculated_revenue:,.2f}"
            )
            st.write(
                f"Model prediction: ₹{prediction:,.2f}"
            )
            st.write(
                "The model estimate may differ from the direct "
                "formula because the decision tree learns from "
                "training examples."
            )

    except FileNotFoundError:
        st.error(
            "Trained model not found. Run "
            "'python ml_model.py' first."
        )
    except Exception as error:
        st.error(f"Prediction failed: {error}")

st.divider()

st.caption(
    "Built with Python, Streamlit, Pandas and Scikit-Learn."
)
